language: php

php:
    - "7.3"

git:
  depth: 10

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
    - echo "memory_limit=3G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - phpenv config-rm xdebug.ini
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - |
        echo "apc.enabled=1
        apc.enable_cli=1
        apc.use_request_time=0
        " > ./apc.ini
    - phpenv config-add ./apc.ini
    - yes '' | pecl install -f apcu-5.1.17
    - printf "\n" | pecl install imagick
    - composer self-update --no-interaction

install:
    - composer install --prefer-dist --no-interaction --no-scripts

script:
    - ./vendor/bin/php-cs-fixer --rules=@PSR2 --dry-run -v fix src
    - ./vendor/bin/phpspec run
