services:
    pim_powerling.form.create_projects:
        class: 'Pim\Bundle\PowerlingBundle\Project\Form\CreateProjectType'
        arguments:
            - '@pim_catalog.repository.locale'
            - '@pim_powerling.repository.webapi'
            - []
        tags:
            - { name: form.type, alias: powerling_create_projects }

    pim_powerling.remover.project:
        class: 'Akeneo\Tool\Bundle\StorageUtilsBundle\Doctrine\Common\Remover\BaseRemover'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - 'Pim\Bundle\PowerlingBundle\Entity\Project'

    pim_powerling.project.builder:
        class: 'Pim\Bundle\PowerlingBundle\Project\Builder'
        arguments:
            - '@oro_config.global'
            - '@akeneo_storage_utils.doctrine.object_detacher'
            - '@monolog.logger.powerling'
            - '@pim_catalog.repository.attribute'
        tags:
            - { name: monolog.logger, channel: powerling }
