services:
    pim_powerling.controller.rest:
        class: Pim\Bundle\PowerlingBundle\Controller\PowerlingRestController
        arguments:
            - '@pim_powerling.repository.webapi'

    pim_powerling.form.create_projects:
        class: Pim\Bundle\PowerlingBundle\Project\Form\CreateProjectType
        arguments:
            - '@pim_catalog.repository.locale'
            - '@pim_powerling.repository.webapi'
            - []
        tags:
            - { name: form.type, alias: powerling_create_projects }

    pim_powerling.saver.project:
        class: Akeneo\Bundle\StorageUtilsBundle\Doctrine\Common\Saver\BaseSaver
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - 'Pim\Bundle\PowerlingBundle\Entity\Project'

    pim_powerling.remover.project:
        class: Akeneo\Bundle\StorageUtilsBundle\Doctrine\Common\Remover\BaseRemover
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - 'Pim\Bundle\PowerlingBundle\Entity\Project'

    pim_powerling.repository.webapi:
        class: Pim\Bundle\PowerlingBundle\Api\WebApiRepository
        public: false
        arguments:
            - '@oro_config.global'
            - '%powerling.base_uri%'

    pim_powerling.project.builder:
        class: Pim\Bundle\PowerlingBundle\Project\Builder
        public: false
        arguments:
            - '@oro_config.global'
            - '@monolog.logger.powerling'
        tags:
            - { name: monolog.logger, channel: powerling }

    pim_powerling.document.updater:
        class: Pim\Bundle\PowerlingBundle\Product\Updater
        arguments:
            - '@pim_catalog.repository.product'
            - '@pim_catalog.updater.product'

    pim_powerling.repository.project:
        class: Pim\Bundle\PowerlingBundle\Project\ProjectRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
            - Pim\Bundle\PowerlingBundle\Entity\Project
